CREATE TABLE UserLikePlaylist (
    LikeID SERIAL PRIMARY KEY,
    UserID INT NOT NULL,
    PlaylistID INT NOT NULL,
    LikeDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES user_(id) ON DELETE CASCADE,
    FOREIGN KEY (PlaylistID) REFERENCES Playlist(PlaylistID) ON DELETE CASCADE
);
