CREATE TABLE UserLikeSong (
    UserID INT REFERENCES user_(id) ON DELETE CASCADE,
    SongID INT REFERENCES song(SongID) ON DELETE CASCADE,
    LikeDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (UserID, SongID)
);
